### ISSUE TITLE
Enhancement: Show clock time on hover

### ISSUE THREAD

**Issue by amandamcg** [jasonlong/mater#121]
Would be great if you could hover over the menu icon to see the actual time of the cycle end. For example, it is 1pm with 5 mins remaining, hover would show `Break Ends: 1:05pm` or `Next Break: 1:05pm`

**Comment by jasonlong** [comment]
Thanks @amandamcg. I'll consider this when I address some other updates I have in mind.

**Comment by amandamcg** [comment]
Thanks! And appreciate your effort on Mater, it has been very useful.
