### ISSUE TITLE
version number broken on macOS

### ISSUE THREAD

**Issue by core-code** [jasonlong/mater#124]
i've downloaded version 1.0.5 but it claims to be version 1.0.4 

the CFBundleVersion and CFBundleShortVersionString entries in the Info.plist file have not been properly updated for this release 

<img width="260" alt="Screenshot 2020-11-08 at 20 56 50" src="https://user-images.githubusercontent.com/1261954/98482950-02145580-2205-11eb-9ac1-520a7a2801c1.png">

**Comment by jasonlong** [comment]
Thank you for pointing this out. I'll get them rebuilt with the proper versions :soon:.

**Comment by jasonlong** [comment]
Ok, I updated some dependencies and published `1.0.6` here: https://github.com/jasonlong/mater/releases/tag/v1.0.6

**Comment by core-code** [comment]
thanks i can confirm it is fixed in 1.0.6
