### ISSUE TITLE
The color of menu bar icon / The app won't launch on Big Sur

### ISSUE THREAD

**Issue by mvmalyi** [jasonlong/mater#125]
Seems like the app does not change the icon color when MacOS is in a dark mode (even though it becomes white once the pop-up is open).

[Screenshot 1](https://drive.google.com/file/d/14coxH2BXJqtjR7Wi4jHbOuQXkkC3ou06/view?usp=sharing)
[Screenshot 2](https://drive.google.com/file/d/1lhdi_1VsVaE3JhW1xnEbPWgb8sNEuhwe/view?usp=sharing)

**Comment by jasonlong** [comment]
@mvmalyi I'm not able to reproduce this. Which version of macOS are you using? And are you running the [latest version](https://github.com/jasonlong/mater/releases/tag/v1.0.6) of mater?

**Comment by mvmalyi** [comment]
@jasonlong Yesterday I updated my Mac to Big Sur, that's when the issue came out. This is what I see after installing the latest version of Mater:
<img width="372" alt="Screen Shot" src="https://user-images.githubusercontent.com/53368562/99145671-69089300-2679-11eb-8d95-4d62f0e4f395.png">

**Comment by jasonlong** [comment]
@mvmalyi Could you give this release a try and let me know if it works for you? On one Big Sur machine this works fine and on another I'm getting an error code (which may be unrelated).

https://github.com/jasonlong/mater/releases/tag/v1.0.7-canary.1

**Comment by mvmalyi** [comment]
@jasonlong Hi Jason! Now it launches without any issues occurring. Thanks for a quick response.

**Comment by jasonlong** [comment]
Thanks @mvmalyi. I've published [1.0.7](https://github.com/jasonlong/mater/releases/tag/v1.0.7) w/ this fix.
