### ISSUE TITLE
Windows: Change icon color based on system dark/light theme

### ISSUE THREAD

**Issue by Brin-o** [jasonlong/mater#160]
In Windows 10 the taskbar icon is almost invisible when the light theme is enabled.
![image](https://user-images.githubusercontent.com/49071768/111038891-8b45ce00-842b-11eb-950d-39afdf476d40.png)

**Comment by jasonlong** [comment]
🤔 This *should* just work with the use of the [menubar](https://github.com/maxogden/menubar) module. Unfortunately I don't have a way to test on Windows right now, so I'm going to add a `help wanted` label here.
