### ISSUE TITLE
Broken UI on Ubuntu 17.10

### ISSUE THREAD

**Issue by tassoevan** [jasonlong/mater#23]
- Shows a black icon (like a mask of original icon)
- Menu with only one menu item without visible text
- Clock animation goes to end

![Mater on Ubuntu 17.10](https://user-images.githubusercontent.com/2263066/37185963-d08c3850-2321-11e8-9c92-73e4d8b46cfe.gif)

**Comment by jasonlong** [comment]
Thanks for the report @tassoevan. I can see the icon and menu problems in your gif. I'm not clear on the

> Clock animation goes to end

though. If you hit Start when it's at 0, it'll scroll to 25. If you then hit stop, it'll stay there until you start again. Are you seeing something different?

Anyhow, hopefully someone with Electron experience on Linux will be able to help here.

**Comment by tassoevan** [comment]
Oh, my bad! I now understand how the clock works. I think I was expecting something to warn when timer is running or not.

I'm not very familiar with Electron yet, therefore I can only contact some friends able to give you some insights about this.

**Comment by jasonlong** [comment]
Thanks @tassoevan. Any help is appreciated.

**Comment by jasonlong** [comment]
I'm going to close this for now, but feel free to reopen if this is still a problem w/ Ubuntu.
