### ISSUE TITLE
Add option for disabling sound

### ISSUE THREAD

**Issue by jasonlong** [jasonlong/mater#24]
I have an idea for a simple settings view which would initially just have an "Enable sounds" checkbox (and maybe eventually the ability to set intervals other than 25/5).

**Comment by chibicode** [comment]
I think the sound option can be added to the contextual click menu 👍 

<img width="71" alt="screen shot 2018-03-17 at 4 51 43 pm" src="https://user-images.githubusercontent.com/992008/37561112-7c2b51fe-2a03-11e8-815c-9f397133908d.png">

**Comment by jasonlong** [comment]
Added in #123.
