### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by 0x2CA** [jasonlong/mater#241]
Thank your application, I like it is so minimalistic, but some functions I think should be added, such as timer activity logging and long resting and custom timer

**Comment by 0x2CA** [comment]
I would like to have non-strict mode,pausing, user can arbitrarily pause, skip, reset

**Comment by jasonlong** [comment]
@0x2CA Thanks for the feedback. At this time, I don't have any plans on making mater more configurable – just a minimal 25/5 timer.
