### ISSUE TITLE
The icon doesn't look great on Windows

### ISSUE THREAD

**Issue by ArtskydJ** [jasonlong/mater#26]
![untitled](https://user-images.githubusercontent.com/1833684/37243832-75961590-2445-11e8-8be5-af0a568df363.png)
(The reason it has a glow is because my cursor was hovering over it at the time, but the screenshot hides the cursor.)

It looks like the transparent and non-transparent icons are inverted?
**Edit** I see the source images. They look good. But Windows does a bad job of scaling them down further. Perhaps there could be 16x16 icons for Windows?

Thanks for making this.

**Comment by jasonlong** [comment]
Thanks for the report @ArtskydJ. This seems to be the same problem that Linux users are seeing (#23). FWIW, there's a set of white icons and black icons and both have transparent backgrounds. I'll try to see if I can figure out why the white ones aren't the default.

**Comment by ankurshva** [comment]
True! It should be white in color like the others! I can't see it! I was confused but I figured it out! 💃 
![image](https://user-images.githubusercontent.com/32816786/37285380-dd897404-2624-11e8-9ec5-2cd7f0d7fe02.png)

**Comment by EanKeen** [comment]
I seem to have this issue as well.

<img src="https://user-images.githubusercontent.com/24364012/37867223-41f7a010-2f52-11e8-8c7f-f3a90e18c92d.png" alt="alt text" width="whatever" height="225">
