### ISSUE TITLE
Port to Tauri

### ISSUE THREAD

**Issue by netomarchiori** [jasonlong/mater#270]
hey Jason, this tool is great! 

I'm working to port mater to Tauri (https://tauri.app/) although it may not be a menubar but a floating window instead.

I'll circle back once I have a working version =]

**Comment by jasonlong** [comment]
Oh nice, I look forward to seeing it :metal:

**Comment by jasonlong** [comment]
@netomarchiori I'm going to close this since there's nothing actionable on this end. Let me know if you end up getting this built.
