### ISSUE TITLE
Mater opens at top of screen with taskbar at bottom (Windows 11)

### ISSUE THREAD

**Issue by jroyvde** [jasonlong/mater#281]
Microsoft Windows 11 Home
Version	10.0.22621 Build 22621
Mater 1.0.10

On my system, the program window appears at the top of the screen rather than adjacent to the taskbar icon.

Wasn't able to get a screenshot as the window would vanish when attempting to do so. But it looks like the horizontal alignment of the window is where it should be, it's just stuck to the very top of the screen rather than the bottom.

**Comment by jasonlong** [comment]
@jroyvde Unfortunately I don't have access to a PC to test and fix this. I'll leave this open in case someone is able to help out.

**Comment by laurensiusadi** [comment]
Possible fix here https://github.com/maxogden/menubar/issues/435#issuecomment-1581628798
