### ISSUE TITLE
Mater window shows on bottom when my taskbar is on top

### ISSUE THREAD

**Issue by laurensiusadi** [jasonlong/mater#29]
![2018-03-12_14-58-45](https://user-images.githubusercontent.com/5661040/37271562-f48e4c20-2605-11e8-8cf1-2afabeb4ce96.png)

**Comment by jasonlong** [comment]
As best I can tell, this is handled by the [menubar](https://github.com/maxogden/menubar) module I'm using. I've opened [an issue](https://github.com/maxogden/menubar/issues/189) on that repo to ask about it.

**Comment by laurensiusadi** [comment]
Found a workaround from another repo, haven't tried but owner claim it fixes the problem https://github.com/inns/mak-mini/commit/fc5a6165051e7f0bf8f2ab93e7b20292e35a779c
I think you should try this.

**Comment by jasonlong** [comment]
Thanks for that pointer @laurensiusadi. If won't have a way of confirming that this actually works since I only have Mac computers. Would you be willing to try it out if I create a version for you?

**Comment by laurensiusadi** [comment]
Yeah sure @jasonlong, I'll test it on my Windows
