### ISSUE TITLE
Button label not centered on Windows

### ISSUE THREAD

**Issue by jasonlong** [jasonlong/mater#30]
I've noticed on various screenshots that the button label is not centered. This is happening on Windows at least – not sure about Linux.

![37243832-75961590-2445-11e8-8be5-af0a568df363](https://user-images.githubusercontent.com/6104/37285639-f2c4facc-25d5-11e8-8691-e07918d9e5f3.png)

**Comment by laurensiusadi** [comment]
Commenting main.css line 147 `width: 80px;` fixes the problem

Before
![picasaphotoviewer_2019-03-05_20-41-57](https://user-images.githubusercontent.com/5661040/53809372-2aa37100-3f87-11e9-9613-9012e5d9e2ae.png)
After
![picasaphotoviewer_2019-03-05_20-42-08](https://user-images.githubusercontent.com/5661040/53809378-2bd49e00-3f87-11e9-9ab4-f137c03244de.png)

**Comment by jasonlong** [comment]
@laurensiusadi It took me a minute to remember why I had that `width` setting in there. I want to avoid having the button change sizes when toggling between the start and stop states and removing the `width` altogether causes a slight shift.

Could you see if changing `width: 80px` to `min-width: 80px` works on Windows?

**Comment by laurensiusadi** [comment]
@jasonlong `min-width: 80px` works. The Start button measures 92px and stop button 91px on my screen.

I'd suggest changing padding to `padding: 0.5em 0;` the text inside button is centered anyway with `text-align: center`. That way you always get 80px width on the button regarding text inside the button.

![2019-03-06_09-23-09](https://user-images.githubusercontent.com/5661040/53851545-9fab9080-3ff1-11e9-9cb3-4fbb71eb8bb7.png)
![2019-03-06_09-23-00](https://user-images.githubusercontent.com/5661040/53851548-a0442700-3ff1-11e9-9f92-452893d899a9.png)

**Comment by jasonlong** [comment]
This is now available in [1.0.4](https://github.com/jasonlong/mater/releases/tag/v1.0.4).
