### ISSUE TITLE
Help with Linux and Windows Testing

### ISSUE THREAD

**Issue by streeetlamp** [jasonlong/mater#32]
Hi, I would happily offer to run tests on machines natively running Windows 10 and a variety of Linux flavors. Let me know if this helps at all.

**Comment by jasonlong** [comment]
@streeetlamp That would be suuuuper helpful! I had thought about opening an issue asking for someone to help w/ Windows and Linux.

Are you comfortable running the app in dev mode w/ `npm` or would you prefer packaged binaries?

**Comment by streeetlamp** [comment]
@jasonlong woops sorry for the delayed response. I would definitely be comfortable running in dev mode w/ npm on Linux, not sure about Windows (never have)
