### ISSUE TITLE
Logo proposal for MATER

### ISSUE THREAD

**Issue by ggabogarcia** [jasonlong/mater#42]
Hi, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by jasonlong** [comment]
Hey thanks for the interest @ggabogarcia, but I don't have a need for a logo at this point. The app has [an icon](https://github.com/jasonlong/mater/blob/master/mater.png) that works for my purposes.
