### ISSUE TITLE
packaging is broken

### ISSUE THREAD

**Issue by 4ndrej** [jasonlong/mater#47]
Your packaging is broken.

in Mater-linux-x64.zip there is:
Mater-linux-x64/resources/app/Mater-darwin-x64.zip
Mater-linux-x64/resources/app/Mater-win32-x64.zip
Mater-linux-x64/resources/app/Mater-linux-x64.zip
each file takes about 50MB. That's the reason why your releases have 200MB.

The `Mater-linux-x64/resources/app/Mater-linux-x64.zip` contains all the app, the rest is bloat and should be removed in packaging script.

**Comment by jasonlong** [comment]
Well that's embarrassing 😅. Thanks for the heads up. I've updated the zips for the latest release.
