### ISSUE TITLE
Add sliding UI

### ISSUE THREAD

**Issue by jasonlong** [jasonlong/mater#5]
Time to add the actual styling and sliding countdown display. Would be nice to convert the placeholder stylesheet to scss as part of this.

**Comment by BekoBou** [comment]
You can find similar project — Pomodoro Timer on [CodePen](http://codepen.io/rrorg/pen/NqowJw/)

![Pomodoro Timer](https://d13yacurqjgara.cloudfront.net/users/921279/screenshots/2190805/pomodoro.png)

**Comment by jasonlong** [comment]
Nice reference @BekoBou, thanks. I'm hoping I can find a way to implement this so that it doesn't kill the CPU though. 😬
