### ISSUE TITLE
Add a possibility to select the monitor where the timer will appear

### ISSUE THREAD

**Issue by Kartm** [jasonlong/mater#53]
I'm using Windows build v1.0.3.
When 25 minutes elapsed, the 5 minute green timer appeared, but on my second monitor.
Are there any plans to add an option to select where to display the timer?

**Comment by jasonlong** [comment]
I don't currently have much control over this since I'm relying on the functionality of this [menubar](https://github.com/maxogden/menubar) package. If I come across anything that might help address this problem, I'll investigate further.
